# Generated by Django 3.1.7 on 2021-02-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
