version: '3'

services:
  database:
    container_name: project-mysql
    image: mysql
    environment:
      MYSQL_PASSWORD: spring
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: spring
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
  cache:
    container_name: project-redis
    image: redis
    ports:
      - '6379:6379'
