version: '3'

services:
  nginx:
    container_name: project-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/:/usr/share/nginx/html/
      - ./staticfiles:/static
    ports:
      - 80:80
    restart: always
  backend:
    build: ./backend
    command: >
      bash -c "python manage.py migrate &&
             gunicorn project_django.wsgi:application --bind 0.0.0.0:8000"
    
    depends_on:
      - database
    volumes:
      - ./staticfiles:/staticfiles
    expose:
      - "8080"
    restart: always
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_USER: django
      POSTGRES_DB: djangodb
    ports:
      - "5432:5432"
